name: Django
on:
  push:
    branches: [ newrest ]
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}} 
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /home
            git clone https://github.com/VictorKudrin/rest.git
            cd rest/api
            . venv/bin/activate
            python3 manage.py runserver